### PR TITLE
theme switch fixed, new nameplate anim

### PR DESCRIPTION
**Pull request by failcoder**

### CODE REVIEW

**Comment by penguinsane** [comment]
Is the new nameplate animation the white glow around it? http://puu.sh/fNHGF/9b96f28d44.jpg

If so, I was actually going to report it as a bug. It's really distracting and I feel like it's not as clear as it used to be. :(

**Comment by failcoder** [comment]
Just merged the most recent changes, try these and let me know

**Comment by penguinsane** [comment]
Much better, and the arrow is really neat! I can see it being handy, and it gives it a nice touch.

Since this is also where it looked like this changed, with the theme stuff, the loot rolls are a bit dark and the timer contrast isn't as good as it was before. The epic items in particular. Maybe the background of the roll timer could be a bit lighter or darker for contrast, and the names of the items be the color of their rarity?

http://puu.sh/fNM41/2ec04babc3.jpg
http://puu.sh/fNHEZ/a5c4252b55.jpg

**Comment by failcoder** [comment]
Is that with the default theme? or is it "Simple"?

**Comment by failcoder** [comment]
Updated

**Pull request merged**
